### ISSUE TITLE
get a error when use this plugin

### ISSUE THREAD

**Issue by zuisong** [itsdouges/vite_plugin_deno_resolve#5]
```
❯ deno run -A  npm:vite  build
vite v4.0.3 building for production...
✓ 0 modules transformed.
[commonjs--resolver] Cannot read properties of undefined (reading 'indexOf')
error during build:
TypeError: Cannot read properties of undefined (reading 'indexOf')
    at Object.resolveId (https://deno.land/x/vite_plugin_deno_resolve@0.4.0/src/https-resolve.ts:50:20)
    at file:///Users/chen/Library/Caches/deno/npm/registry.npmjs.org/rollup/3.8.1/dist/es/shared/rollup.js:23560:40
```

deno version:  v1.29.1

**Comment by zuisong** [comment]
```typescript
// vite.config.mts
import { defineConfig } from 'npm:vite@4.0.3';
import denoResolve from "https://deno.land/x/vite_plugin_deno_resolve@0.4.0/mod.ts";
export default defineConfig({
  esbuild: {},
  build: {
    lib: {
      entry: "./src/index.ts",
      name: "notion-kroki",
      formats: ["es", "cjs", "umd"],
      fileName: "notion-kroki",
    },
    minify: false,
    sourcemap: true,
  },

  plugins: [denoResolve()],
});
```

```typescript
// index.ts
//demo code
export { zlibSync } from "npm:fflate";
console.log("Hello")
```

**Comment by itsdouges** [comment]
Hey mate, currently npm specifiers aren't supported. You can follow this issue: https://github.com/itsdouges/vite_plugin_deno_resolve/issues/2 which hopes to implement it.
